### ISSUE TITLE
取反表达式出现检查报错

### ISSUE THREAD

**Issue by aoguai** [gkd-kit/tools#3]
使用v1.8.0-beta.3版本新支持的取反表达式编写代码出现检查报错。
报错如下：
```
          throw new Error(
                ^


Error: Invalid matches selector: [childCount<7] > [name!$=".CheckBox"][childCount=0][visibleToUser=true][height>0&&width>0][(text.length<10&&(text*="跳过"||text*="跳過"||text~="(?is).*skip.*"))||id~="(?is).*tt_splash_skip_btn"||vid~="(?is).*skip.*"||(vid~="(?is).*count.*"&&vid~="(?is).*down.*"&&!(vid~="(?is).*load.*")&&!(vid~="(?is).*hour.*")&&!(vid~="(?is).*minute.*")&&!(vid~="(?is).*add.*")&&!(vid~="(?is).*ead.*"))||desc*="跳过"||desc~="(?is).*skip.*"][!(text~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]")][!(desc~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]")] in subscription[id=86,name=奥怪的GKD订阅] global group[key=0,name=开屏广告] rule[key=0,name=undefined]
    at <anonymous> (D:\sj\project\TypeScript\subscription\node_modules\.pnpm\@gkd-kit+tools@0.2.0_@gkd-kit+api@0.1.0_json5@2.2.3\node_modules\@gkd-kit\tools\dist\index.mjs:711:17)
    at Array.forEach (<anonymous>)
    at <anonymous> (D:\sj\project\TypeScript\subscription\node_modules\.pnpm\@gkd-kit+tools@0.2.0_@gkd-kit+api@0.1.0_json5@2.2.3\node_modules\@gkd-kit\tools\dist\index.mjs:706:18)
    at Array.forEach (<anonymous>)
    at checkSelector (D:\sj\project\TypeScript\subscription\node_modules\.pnpm\@gkd-kit+tools@0.2.0_@gkd-kit+api@0.1.0_json5@2.2.3\node_modules\@gkd-kit\tools\dist\index.mjs:705:30)
    at checkSubscription (D:\sj\project\TypeScript\subscription\node_modules\.pnpm\@gkd-kit+tools@0.2.0_@gkd-kit+api@0.1.0_json5@2.2.3\node_modules\@gkd-kit\tools\dist\index.mjs:783:3)
    at <anonymous> (D:\sj\project\TypeScript\subscription\scripts\check.ts:4:1) {
  [cause]: GkdSyntaxError: expected (_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ in selector at position 259, but got !
      at gkdAssert (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\GkdSyntaxError.kt:26:15)
      at ParserSet.protoOf.cl (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\ParserSet.kt:462:21)
      at ParserSet.protoOf.cl (D:\sj\project\TypeScript\subscription\node_modules\.pnpm\@gkd-kit+selector@0.0.25\node_modules\@gkd-kit\selector\kotlin\src\kotlin\util\Standard.kt:158:11416)
      at Parser.ParserSet$attrParser$lambda (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\ParserSet.kt:517:19)
      at Parser.protoOf.xk (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\Parser.kt:7:56)
      at Parser.ParserSet$selectorUnitParser$lambda (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\ParserSet.kt:538:30)
      at Parser.protoOf.xk (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\Parser.kt:7:56)
      at Parser.ParserSet$connectSelectorParser$lambda (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\ParserSet.kt:568:34)
      at Parser.protoOf.xk (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\Parser.kt:7:56)
      at ParserSet.ParserSet$selectorParser$lambda (D:\sj\project\TypeScript\subscription\node_modules\src\commonMain\kotlin\li\songe\selector\parser\ParserSet.kt:585:40) {
    expectedValue: '(_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
    position: 259,
    source: '[childCount<7] > [name!$=".CheckBox"][childCount=0][visibleToUser=true][height>0&&width>0][(text.length<10&&(text*="跳过"||text*="跳過"||text~="(?is).*skip.*"))||id~="(?is).*tt_splash_skip_btn"||vid~="(?is).*skip.*"||(vid~="(?is).*count.*"&&vid~="(?is).*down.*"&&!(vid~="(?is).*load.*")&&!(vid~="(?is).*hour.*")&&!(vid~="(?is).*minute.*")&&!(vid~="(?is).*add.*")&&!(vid~="(?is).*ead.*"))||desc*="跳过"||desc~="(?is).*skip.*"][!(text~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]")][!(desc~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]")]',
    ab_1: null,
    cause: null
  }
}

Node.js v20.15.0
 ELIFECYCLE  Command failed with exit code 1.
```

对应规则如下：
```
[childCount<7] > [name!$=".CheckBox"][childCount=0][visibleToUser=true][height>0&&width>0][(text.length<10&&(text*="跳过"||text*="跳過"||text~="(?is).*skip.*"))||id~="(?is).*tt_splash_skip_btn"||vid~="(?is).*skip.*"||(vid~="(?is).*count.*"&&vid~="(?is).*down.*"&&!(vid~="(?is).*load.*")&&!(vid~="(?is).*hour.*")&&!(vid~="(?is).*minute.*")&&!(vid~="(?is).*add.*")&&!(vid~="(?is).*ead.*"))||desc*="跳过"||desc~="(?is).*skip.*"][!(text~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]")][!(desc~="([01]?[0-9]|2[0-3])[:：][0-5][0-9]")]
```

且在[快照](https://i.gkd.li/i/15912956)能正常匹配

![image](https://github.com/gkd-kit/tools/assets/34203474/586c1914-019d-4fd0-9467-1d5220eeae44)

**Comment by aoguai** [comment]
应该是依赖版本没更上
